#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '12':
        pose: /mavros/mocap/pose
        pose2d: /mavros/mocap/pose2d
        child_frame_id: base_link
        parent_frame_id: world
optitrack_config:
        multicast_address: 224.0.0.1
