; Auto-generated. Do not edit!


(cl:in-package aeplanner-msg)


;//! \htmlinclude aeplannerGoal.msg.html

(cl:defclass <aeplannerGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (actions_taken
    :reader actions_taken
    :initarg :actions_taken
    :type cl:integer
    :initform 0))
)

(cl:defclass aeplannerGoal (<aeplannerGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <aeplannerGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'aeplannerGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name aeplanner-msg:<aeplannerGoal> is deprecated: use aeplanner-msg:aeplannerGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <aeplannerGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader aeplanner-msg:header-val is deprecated.  Use aeplanner-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'actions_taken-val :lambda-list '(m))
(cl:defmethod actions_taken-val ((m <aeplannerGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader aeplanner-msg:actions_taken-val is deprecated.  Use aeplanner-msg:actions_taken instead.")
  (actions_taken m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <aeplannerGoal>) ostream)
  "Serializes a message object of type '<aeplannerGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (cl:let* ((signed (cl:slot-value msg 'actions_taken)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <aeplannerGoal>) istream)
  "Deserializes a message object of type '<aeplannerGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'actions_taken) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<aeplannerGoal>)))
  "Returns string type for a message object of type '<aeplannerGoal>"
  "aeplanner/aeplannerGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'aeplannerGoal)))
  "Returns string type for a message object of type 'aeplannerGoal"
  "aeplanner/aeplannerGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<aeplannerGoal>)))
  "Returns md5sum for a message object of type '<aeplannerGoal>"
  "8af38301301363c106591cce65e2a43e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'aeplannerGoal)))
  "Returns md5sum for a message object of type 'aeplannerGoal"
  "8af38301301363c106591cce65e2a43e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<aeplannerGoal>)))
  "Returns full string definition for message of type '<aeplannerGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%Header header~%int32 actions_taken~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'aeplannerGoal)))
  "Returns full string definition for message of type 'aeplannerGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%Header header~%int32 actions_taken~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <aeplannerGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <aeplannerGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'aeplannerGoal
    (cl:cons ':header (header msg))
    (cl:cons ':actions_taken (actions_taken msg))
))
