; Auto-generated. Do not edit!


(cl:in-package aeplanner-msg)


;//! \htmlinclude aeplannerFeedback.msg.html

(cl:defclass <aeplannerFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass aeplannerFeedback (<aeplannerFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <aeplannerFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'aeplannerFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name aeplanner-msg:<aeplannerFeedback> is deprecated: use aeplanner-msg:aeplannerFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <aeplannerFeedback>) ostream)
  "Serializes a message object of type '<aeplannerFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <aeplannerFeedback>) istream)
  "Deserializes a message object of type '<aeplannerFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<aeplannerFeedback>)))
  "Returns string type for a message object of type '<aeplannerFeedback>"
  "aeplanner/aeplannerFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'aeplannerFeedback)))
  "Returns string type for a message object of type 'aeplannerFeedback"
  "aeplanner/aeplannerFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<aeplannerFeedback>)))
  "Returns md5sum for a message object of type '<aeplannerFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'aeplannerFeedback)))
  "Returns md5sum for a message object of type 'aeplannerFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<aeplannerFeedback>)))
  "Returns full string definition for message of type '<aeplannerFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'aeplannerFeedback)))
  "Returns full string definition for message of type 'aeplannerFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <aeplannerFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <aeplannerFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'aeplannerFeedback
))
