// Generated by gencpp from file pigain/BestNode.msg
// DO NOT EDIT!


#ifndef PIGAIN_MESSAGE_BESTNODE_H
#define PIGAIN_MESSAGE_BESTNODE_H

#include <ros/service_traits.h>


#include <pigain/BestNodeRequest.h>
#include <pigain/BestNodeResponse.h>


namespace pigain
{

struct BestNode
{

typedef BestNodeRequest Request;
typedef BestNodeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BestNode
} // namespace pigain


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pigain::BestNode > {
  static const char* value()
  {
    return "6ef124f7650f66bfe5fcee2adc4b7d2c";
  }

  static const char* value(const ::pigain::BestNode&) { return value(); }
};

template<>
struct DataType< ::pigain::BestNode > {
  static const char* value()
  {
    return "pigain/BestNode";
  }

  static const char* value(const ::pigain::BestNode&) { return value(); }
};


// service_traits::MD5Sum< ::pigain::BestNodeRequest> should match 
// service_traits::MD5Sum< ::pigain::BestNode > 
template<>
struct MD5Sum< ::pigain::BestNodeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pigain::BestNode >::value();
  }
  static const char* value(const ::pigain::BestNodeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pigain::BestNodeRequest> should match 
// service_traits::DataType< ::pigain::BestNode > 
template<>
struct DataType< ::pigain::BestNodeRequest>
{
  static const char* value()
  {
    return DataType< ::pigain::BestNode >::value();
  }
  static const char* value(const ::pigain::BestNodeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pigain::BestNodeResponse> should match 
// service_traits::MD5Sum< ::pigain::BestNode > 
template<>
struct MD5Sum< ::pigain::BestNodeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pigain::BestNode >::value();
  }
  static const char* value(const ::pigain::BestNodeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pigain::BestNodeResponse> should match 
// service_traits::DataType< ::pigain::BestNode > 
template<>
struct DataType< ::pigain::BestNodeResponse>
{
  static const char* value()
  {
    return DataType< ::pigain::BestNode >::value();
  }
  static const char* value(const ::pigain::BestNodeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PIGAIN_MESSAGE_BESTNODE_H
