// Generated by gencpp from file pigain/BestNodeResponse.msg
// DO NOT EDIT!


#ifndef PIGAIN_MESSAGE_BESTNODERESPONSE_H
#define PIGAIN_MESSAGE_BESTNODERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace pigain
{
template <class ContainerAllocator>
struct BestNodeResponse_
{
  typedef BestNodeResponse_<ContainerAllocator> Type;

  BestNodeResponse_()
    : best_node()
    , gain(0.0)  {
    }
  BestNodeResponse_(const ContainerAllocator& _alloc)
    : best_node(_alloc)
    , gain(0.0)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _best_node_type;
  _best_node_type best_node;

   typedef double _gain_type;
  _gain_type gain;





  typedef boost::shared_ptr< ::pigain::BestNodeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pigain::BestNodeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BestNodeResponse_

typedef ::pigain::BestNodeResponse_<std::allocator<void> > BestNodeResponse;

typedef boost::shared_ptr< ::pigain::BestNodeResponse > BestNodeResponsePtr;
typedef boost::shared_ptr< ::pigain::BestNodeResponse const> BestNodeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pigain::BestNodeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pigain::BestNodeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pigain

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'pigain': ['/home/idris/catkin_ws/src/aeplanner/pigain/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pigain::BestNodeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pigain::BestNodeResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pigain::BestNodeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pigain::BestNodeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pigain::BestNodeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pigain::BestNodeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pigain::BestNodeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa72b0c3593d8d5143961cb50a19c5e1";
  }

  static const char* value(const ::pigain::BestNodeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaa72b0c3593d8d51ULL;
  static const uint64_t static_value2 = 0x43961cb50a19c5e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::pigain::BestNodeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pigain/BestNodeResponse";
  }

  static const char* value(const ::pigain::BestNodeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pigain::BestNodeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] best_node\n\
float64 gain\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::pigain::BestNodeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pigain::BestNodeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.best_node);
      stream.next(m.gain);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BestNodeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pigain::BestNodeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pigain::BestNodeResponse_<ContainerAllocator>& v)
  {
    s << indent << "best_node[]" << std::endl;
    for (size_t i = 0; i < v.best_node.size(); ++i)
    {
      s << indent << "  best_node[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.best_node[i]);
    }
    s << indent << "gain: ";
    Printer<double>::stream(s, indent + "  ", v.gain);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIGAIN_MESSAGE_BESTNODERESPONSE_H
