// Generated by gencpp from file pigain/Node.msg
// DO NOT EDIT!


#ifndef PIGAIN_MESSAGE_NODE_H
#define PIGAIN_MESSAGE_NODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace pigain
{
template <class ContainerAllocator>
struct Node_
{
  typedef Node_<ContainerAllocator> Type;

  Node_()
    : position()
    , yaw(0.0)
    , gain(0.0)  {
    }
  Node_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , yaw(0.0)
    , gain(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _gain_type;
  _gain_type gain;





  typedef boost::shared_ptr< ::pigain::Node_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pigain::Node_<ContainerAllocator> const> ConstPtr;

}; // struct Node_

typedef ::pigain::Node_<std::allocator<void> > Node;

typedef boost::shared_ptr< ::pigain::Node > NodePtr;
typedef boost::shared_ptr< ::pigain::Node const> NodeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pigain::Node_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pigain::Node_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pigain

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'pigain': ['/home/idris/catkin_ws/src/aeplanner/pigain/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pigain::Node_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pigain::Node_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pigain::Node_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pigain::Node_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pigain::Node_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pigain::Node_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pigain::Node_<ContainerAllocator> >
{
  static const char* value()
  {
    return "621af42ede91547e9cdc2946e4c6e175";
  }

  static const char* value(const ::pigain::Node_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x621af42ede91547eULL;
  static const uint64_t static_value2 = 0x9cdc2946e4c6e175ULL;
};

template<class ContainerAllocator>
struct DataType< ::pigain::Node_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pigain/Node";
  }

  static const char* value(const ::pigain::Node_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pigain::Node_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point position\n\
float64 yaw\n\
float64 gain\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::pigain::Node_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pigain::Node_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.yaw);
      stream.next(m.gain);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Node_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pigain::Node_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pigain::Node_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "gain: ";
    Printer<double>::stream(s, indent + "  ", v.gain);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIGAIN_MESSAGE_NODE_H
