// Generated by gencpp from file pigain/Query.msg
// DO NOT EDIT!


#ifndef PIGAIN_MESSAGE_QUERY_H
#define PIGAIN_MESSAGE_QUERY_H

#include <ros/service_traits.h>


#include <pigain/QueryRequest.h>
#include <pigain/QueryResponse.h>


namespace pigain
{

struct Query
{

typedef QueryRequest Request;
typedef QueryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Query
} // namespace pigain


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pigain::Query > {
  static const char* value()
  {
    return "cfbeffb732fb085ef41c291ee034ea65";
  }

  static const char* value(const ::pigain::Query&) { return value(); }
};

template<>
struct DataType< ::pigain::Query > {
  static const char* value()
  {
    return "pigain/Query";
  }

  static const char* value(const ::pigain::Query&) { return value(); }
};


// service_traits::MD5Sum< ::pigain::QueryRequest> should match 
// service_traits::MD5Sum< ::pigain::Query > 
template<>
struct MD5Sum< ::pigain::QueryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pigain::Query >::value();
  }
  static const char* value(const ::pigain::QueryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pigain::QueryRequest> should match 
// service_traits::DataType< ::pigain::Query > 
template<>
struct DataType< ::pigain::QueryRequest>
{
  static const char* value()
  {
    return DataType< ::pigain::Query >::value();
  }
  static const char* value(const ::pigain::QueryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pigain::QueryResponse> should match 
// service_traits::MD5Sum< ::pigain::Query > 
template<>
struct MD5Sum< ::pigain::QueryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pigain::Query >::value();
  }
  static const char* value(const ::pigain::QueryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pigain::QueryResponse> should match 
// service_traits::DataType< ::pigain::Query > 
template<>
struct DataType< ::pigain::QueryResponse>
{
  static const char* value()
  {
    return DataType< ::pigain::Query >::value();
  }
  static const char* value(const ::pigain::QueryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PIGAIN_MESSAGE_QUERY_H
