// Generated by gencpp from file dd_control/Velocity.msg
// DO NOT EDIT!


#ifndef DD_CONTROL_MESSAGE_VELOCITY_H
#define DD_CONTROL_MESSAGE_VELOCITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace dd_control
{
template <class ContainerAllocator>
struct Velocity_
{
  typedef Velocity_<ContainerAllocator> Type;

  Velocity_()
    : header()
    , current_xy_vel(0.0)
    , current_z_vel(0.0)
    , desired_xy_vel(0.0)
    , desired_z_vel(0.0)  {
    }
  Velocity_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , current_xy_vel(0.0)
    , current_z_vel(0.0)
    , desired_xy_vel(0.0)
    , desired_z_vel(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _current_xy_vel_type;
  _current_xy_vel_type current_xy_vel;

   typedef double _current_z_vel_type;
  _current_z_vel_type current_z_vel;

   typedef double _desired_xy_vel_type;
  _desired_xy_vel_type desired_xy_vel;

   typedef double _desired_z_vel_type;
  _desired_z_vel_type desired_z_vel;





  typedef boost::shared_ptr< ::dd_control::Velocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dd_control::Velocity_<ContainerAllocator> const> ConstPtr;

}; // struct Velocity_

typedef ::dd_control::Velocity_<std::allocator<void> > Velocity;

typedef boost::shared_ptr< ::dd_control::Velocity > VelocityPtr;
typedef boost::shared_ptr< ::dd_control::Velocity const> VelocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dd_control::Velocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dd_control::Velocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dd_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'dd_control': ['/home/idris/catkin_ws/src/dd_control/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dd_control::Velocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dd_control::Velocity_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dd_control::Velocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dd_control::Velocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dd_control::Velocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dd_control::Velocity_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dd_control::Velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0f5ff12a080e44f8a1d763086e8f0b5e";
  }

  static const char* value(const ::dd_control::Velocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0f5ff12a080e44f8ULL;
  static const uint64_t static_value2 = 0xa1d763086e8f0b5eULL;
};

template<class ContainerAllocator>
struct DataType< ::dd_control::Velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd_control/Velocity";
  }

  static const char* value(const ::dd_control::Velocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dd_control::Velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 current_xy_vel\n\
float64 current_z_vel\n\
float64 desired_xy_vel\n\
float64 desired_z_vel\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::dd_control::Velocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dd_control::Velocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.current_xy_vel);
      stream.next(m.current_z_vel);
      stream.next(m.desired_xy_vel);
      stream.next(m.desired_z_vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Velocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dd_control::Velocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dd_control::Velocity_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "current_xy_vel: ";
    Printer<double>::stream(s, indent + "  ", v.current_xy_vel);
    s << indent << "current_z_vel: ";
    Printer<double>::stream(s, indent + "  ", v.current_z_vel);
    s << indent << "desired_xy_vel: ";
    Printer<double>::stream(s, indent + "  ", v.desired_xy_vel);
    s << indent << "desired_z_vel: ";
    Printer<double>::stream(s, indent + "  ", v.desired_z_vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DD_CONTROL_MESSAGE_VELOCITY_H
