// Generated by gencpp from file rrtplanner/rrtGoal.msg
// DO NOT EDIT!


#ifndef RRTPLANNER_MESSAGE_RRTGOAL_H
#define RRTPLANNER_MESSAGE_RRTGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/PoseArray.h>

namespace rrtplanner
{
template <class ContainerAllocator>
struct rrtGoal_
{
  typedef rrtGoal_<ContainerAllocator> Type;

  rrtGoal_()
    : start()
    , goal_poses()  {
    }
  rrtGoal_(const ContainerAllocator& _alloc)
    : start(_alloc)
    , goal_poses(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _start_type;
  _start_type start;

   typedef  ::geometry_msgs::PoseArray_<ContainerAllocator>  _goal_poses_type;
  _goal_poses_type goal_poses;





  typedef boost::shared_ptr< ::rrtplanner::rrtGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rrtplanner::rrtGoal_<ContainerAllocator> const> ConstPtr;

}; // struct rrtGoal_

typedef ::rrtplanner::rrtGoal_<std::allocator<void> > rrtGoal;

typedef boost::shared_ptr< ::rrtplanner::rrtGoal > rrtGoalPtr;
typedef boost::shared_ptr< ::rrtplanner::rrtGoal const> rrtGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rrtplanner::rrtGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rrtplanner::rrtGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rrtplanner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/melodic/share/nav_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'rrtplanner': ['/home/idris/catkin_ws/devel/.private/rrtplanner/share/rrtplanner/msg'], 'visualization_msgs': ['/opt/ros/melodic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rrtplanner::rrtGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rrtplanner::rrtGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rrtplanner::rrtGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rrtplanner::rrtGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rrtplanner::rrtGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rrtplanner::rrtGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rrtplanner::rrtGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e83561ba81ebf93b30fd2df01757c10";
  }

  static const char* value(const ::rrtplanner::rrtGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e83561ba81ebf93ULL;
  static const uint64_t static_value2 = 0xb30fd2df01757c10ULL;
};

template<class ContainerAllocator>
struct DataType< ::rrtplanner::rrtGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rrtplanner/rrtGoal";
  }

  static const char* value(const ::rrtplanner::rrtGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rrtplanner::rrtGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the goal\n\
geometry_msgs/PoseStamped start\n\
geometry_msgs/PoseArray goal_poses\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseArray\n\
# An array of poses with a header for global reference.\n\
\n\
Header header\n\
\n\
Pose[] poses\n\
";
  }

  static const char* value(const ::rrtplanner::rrtGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rrtplanner::rrtGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
      stream.next(m.goal_poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rrtGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rrtplanner::rrtGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rrtplanner::rrtGoal_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.start);
    s << indent << "goal_poses: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseArray_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_poses);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RRTPLANNER_MESSAGE_RRTGOAL_H
