; Auto-generated. Do not edit!


(cl:in-package rrtplanner-msg)


;//! \htmlinclude rrtFeedback.msg.html

(cl:defclass <rrtFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass rrtFeedback (<rrtFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <rrtFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'rrtFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rrtplanner-msg:<rrtFeedback> is deprecated: use rrtplanner-msg:rrtFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <rrtFeedback>) ostream)
  "Serializes a message object of type '<rrtFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <rrtFeedback>) istream)
  "Deserializes a message object of type '<rrtFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<rrtFeedback>)))
  "Returns string type for a message object of type '<rrtFeedback>"
  "rrtplanner/rrtFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'rrtFeedback)))
  "Returns string type for a message object of type 'rrtFeedback"
  "rrtplanner/rrtFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<rrtFeedback>)))
  "Returns md5sum for a message object of type '<rrtFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'rrtFeedback)))
  "Returns md5sum for a message object of type 'rrtFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<rrtFeedback>)))
  "Returns full string definition for message of type '<rrtFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'rrtFeedback)))
  "Returns full string definition for message of type 'rrtFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <rrtFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <rrtFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'rrtFeedback
))
