; Auto-generated. Do not edit!


(cl:in-package rrtplanner-msg)


;//! \htmlinclude rrtGoal.msg.html

(cl:defclass <rrtGoal> (roslisp-msg-protocol:ros-message)
  ((start
    :reader start
    :initarg :start
    :type geometry_msgs-msg:PoseStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PoseStamped))
   (goal_poses
    :reader goal_poses
    :initarg :goal_poses
    :type geometry_msgs-msg:PoseArray
    :initform (cl:make-instance 'geometry_msgs-msg:PoseArray)))
)

(cl:defclass rrtGoal (<rrtGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <rrtGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'rrtGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rrtplanner-msg:<rrtGoal> is deprecated: use rrtplanner-msg:rrtGoal instead.")))

(cl:ensure-generic-function 'start-val :lambda-list '(m))
(cl:defmethod start-val ((m <rrtGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rrtplanner-msg:start-val is deprecated.  Use rrtplanner-msg:start instead.")
  (start m))

(cl:ensure-generic-function 'goal_poses-val :lambda-list '(m))
(cl:defmethod goal_poses-val ((m <rrtGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rrtplanner-msg:goal_poses-val is deprecated.  Use rrtplanner-msg:goal_poses instead.")
  (goal_poses m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <rrtGoal>) ostream)
  "Serializes a message object of type '<rrtGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'start) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_poses) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <rrtGoal>) istream)
  "Deserializes a message object of type '<rrtGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'start) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_poses) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<rrtGoal>)))
  "Returns string type for a message object of type '<rrtGoal>"
  "rrtplanner/rrtGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'rrtGoal)))
  "Returns string type for a message object of type 'rrtGoal"
  "rrtplanner/rrtGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<rrtGoal>)))
  "Returns md5sum for a message object of type '<rrtGoal>"
  "0e83561ba81ebf93b30fd2df01757c10")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'rrtGoal)))
  "Returns md5sum for a message object of type 'rrtGoal"
  "0e83561ba81ebf93b30fd2df01757c10")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<rrtGoal>)))
  "Returns full string definition for message of type '<rrtGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%geometry_msgs/PoseStamped start~%geometry_msgs/PoseArray goal_poses~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%================================================================================~%MSG: geometry_msgs/PoseArray~%# An array of poses with a header for global reference.~%~%Header header~%~%Pose[] poses~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'rrtGoal)))
  "Returns full string definition for message of type 'rrtGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%geometry_msgs/PoseStamped start~%geometry_msgs/PoseArray goal_poses~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%================================================================================~%MSG: geometry_msgs/PoseArray~%# An array of poses with a header for global reference.~%~%Header header~%~%Pose[] poses~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <rrtGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'start))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_poses))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <rrtGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'rrtGoal
    (cl:cons ':start (start msg))
    (cl:cons ':goal_poses (goal_poses msg))
))
