# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from aeplanner/aeplannerResult.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import genpy
import std_msgs.msg

class aeplannerResult(genpy.Message):
  _md5sum = "9455a2480a247f4ce7d9ba7774e790ba"
  _type = "aeplanner/aeplannerResult"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# Define the result
geometry_msgs/PoseStamped pose
geometry_msgs/PoseArray frontiers
bool is_clear
std_msgs/Duration sampling_time
std_msgs/Duration planning_time
std_msgs/Duration collision_check_time
int32 tree_size

================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/PoseArray
# An array of poses with a header for global reference.

Header header

Pose[] poses

================================================================================
MSG: std_msgs/Duration
duration data
"""
  __slots__ = ['pose','frontiers','is_clear','sampling_time','planning_time','collision_check_time','tree_size']
  _slot_types = ['geometry_msgs/PoseStamped','geometry_msgs/PoseArray','bool','std_msgs/Duration','std_msgs/Duration','std_msgs/Duration','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pose,frontiers,is_clear,sampling_time,planning_time,collision_check_time,tree_size

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(aeplannerResult, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.pose is None:
        self.pose = geometry_msgs.msg.PoseStamped()
      if self.frontiers is None:
        self.frontiers = geometry_msgs.msg.PoseArray()
      if self.is_clear is None:
        self.is_clear = False
      if self.sampling_time is None:
        self.sampling_time = std_msgs.msg.Duration()
      if self.planning_time is None:
        self.planning_time = std_msgs.msg.Duration()
      if self.collision_check_time is None:
        self.collision_check_time = std_msgs.msg.Duration()
      if self.tree_size is None:
        self.tree_size = 0
    else:
      self.pose = geometry_msgs.msg.PoseStamped()
      self.frontiers = geometry_msgs.msg.PoseArray()
      self.is_clear = False
      self.sampling_time = std_msgs.msg.Duration()
      self.planning_time = std_msgs.msg.Duration()
      self.collision_check_time = std_msgs.msg.Duration()
      self.tree_size = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.pose.header.seq, _x.pose.header.stamp.secs, _x.pose.header.stamp.nsecs))
      _x = self.pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_7d3I().pack(_x.pose.pose.position.x, _x.pose.pose.position.y, _x.pose.pose.position.z, _x.pose.pose.orientation.x, _x.pose.pose.orientation.y, _x.pose.pose.orientation.z, _x.pose.pose.orientation.w, _x.frontiers.header.seq, _x.frontiers.header.stamp.secs, _x.frontiers.header.stamp.nsecs))
      _x = self.frontiers.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.frontiers.poses)
      buff.write(_struct_I.pack(length))
      for val1 in self.frontiers.poses:
        _v1 = val1.position
        _x = _v1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v2 = val1.orientation
        _x = _v2
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
      _x = self
      buff.write(_get_struct_B7i().pack(_x.is_clear, _x.sampling_time.data.secs, _x.sampling_time.data.nsecs, _x.planning_time.data.secs, _x.planning_time.data.nsecs, _x.collision_check_time.data.secs, _x.collision_check_time.data.nsecs, _x.tree_size))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.pose is None:
        self.pose = geometry_msgs.msg.PoseStamped()
      if self.frontiers is None:
        self.frontiers = geometry_msgs.msg.PoseArray()
      if self.sampling_time is None:
        self.sampling_time = std_msgs.msg.Duration()
      if self.planning_time is None:
        self.planning_time = std_msgs.msg.Duration()
      if self.collision_check_time is None:
        self.collision_check_time = std_msgs.msg.Duration()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.pose.header.seq, _x.pose.header.stamp.secs, _x.pose.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pose.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.pose.pose.position.x, _x.pose.pose.position.y, _x.pose.pose.position.z, _x.pose.pose.orientation.x, _x.pose.pose.orientation.y, _x.pose.pose.orientation.z, _x.pose.pose.orientation.w, _x.frontiers.header.seq, _x.frontiers.header.stamp.secs, _x.frontiers.header.stamp.nsecs,) = _get_struct_7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.frontiers.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.frontiers.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.frontiers.poses = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose()
        _v3 = val1.position
        _x = _v3
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v4 = val1.orientation
        _x = _v4
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        self.frontiers.poses.append(val1)
      _x = self
      start = end
      end += 29
      (_x.is_clear, _x.sampling_time.data.secs, _x.sampling_time.data.nsecs, _x.planning_time.data.secs, _x.planning_time.data.nsecs, _x.collision_check_time.data.secs, _x.collision_check_time.data.nsecs, _x.tree_size,) = _get_struct_B7i().unpack(str[start:end])
      self.is_clear = bool(self.is_clear)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.pose.header.seq, _x.pose.header.stamp.secs, _x.pose.header.stamp.nsecs))
      _x = self.pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_7d3I().pack(_x.pose.pose.position.x, _x.pose.pose.position.y, _x.pose.pose.position.z, _x.pose.pose.orientation.x, _x.pose.pose.orientation.y, _x.pose.pose.orientation.z, _x.pose.pose.orientation.w, _x.frontiers.header.seq, _x.frontiers.header.stamp.secs, _x.frontiers.header.stamp.nsecs))
      _x = self.frontiers.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.frontiers.poses)
      buff.write(_struct_I.pack(length))
      for val1 in self.frontiers.poses:
        _v5 = val1.position
        _x = _v5
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v6 = val1.orientation
        _x = _v6
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
      _x = self
      buff.write(_get_struct_B7i().pack(_x.is_clear, _x.sampling_time.data.secs, _x.sampling_time.data.nsecs, _x.planning_time.data.secs, _x.planning_time.data.nsecs, _x.collision_check_time.data.secs, _x.collision_check_time.data.nsecs, _x.tree_size))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.pose is None:
        self.pose = geometry_msgs.msg.PoseStamped()
      if self.frontiers is None:
        self.frontiers = geometry_msgs.msg.PoseArray()
      if self.sampling_time is None:
        self.sampling_time = std_msgs.msg.Duration()
      if self.planning_time is None:
        self.planning_time = std_msgs.msg.Duration()
      if self.collision_check_time is None:
        self.collision_check_time = std_msgs.msg.Duration()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.pose.header.seq, _x.pose.header.stamp.secs, _x.pose.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pose.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.pose.pose.position.x, _x.pose.pose.position.y, _x.pose.pose.position.z, _x.pose.pose.orientation.x, _x.pose.pose.orientation.y, _x.pose.pose.orientation.z, _x.pose.pose.orientation.w, _x.frontiers.header.seq, _x.frontiers.header.stamp.secs, _x.frontiers.header.stamp.nsecs,) = _get_struct_7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.frontiers.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.frontiers.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.frontiers.poses = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose()
        _v7 = val1.position
        _x = _v7
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v8 = val1.orientation
        _x = _v8
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        self.frontiers.poses.append(val1)
      _x = self
      start = end
      end += 29
      (_x.is_clear, _x.sampling_time.data.secs, _x.sampling_time.data.nsecs, _x.planning_time.data.secs, _x.planning_time.data.nsecs, _x.collision_check_time.data.secs, _x.collision_check_time.data.nsecs, _x.tree_size,) = _get_struct_B7i().unpack(str[start:end])
      self.is_clear = bool(self.is_clear)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B7i = None
def _get_struct_B7i():
    global _struct_B7i
    if _struct_B7i is None:
        _struct_B7i = struct.Struct("<B7i")
    return _struct_B7i
_struct_7d3I = None
def _get_struct_7d3I():
    global _struct_7d3I
    if _struct_7d3I is None:
        _struct_7d3I = struct.Struct("<7d3I")
    return _struct_7d3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
