// Auto-generated. Do not edit!

// (in-package rpl_exploration.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class FlyToFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.distance_to_target = null;
    }
    else {
      if (initObj.hasOwnProperty('distance_to_target')) {
        this.distance_to_target = initObj.distance_to_target
      }
      else {
        this.distance_to_target = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type FlyToFeedback
    // Serialize message field [distance_to_target]
    bufferOffset = _serializer.float32(obj.distance_to_target, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type FlyToFeedback
    let len;
    let data = new FlyToFeedback(null);
    // Deserialize message field [distance_to_target]
    data.distance_to_target = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'rpl_exploration/FlyToFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '7162840b236da25d3abd73cc2177a48e';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define a feedback message
    float32 distance_to_target
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new FlyToFeedback(null);
    if (msg.distance_to_target !== undefined) {
      resolved.distance_to_target = msg.distance_to_target;
    }
    else {
      resolved.distance_to_target = 0.0
    }

    return resolved;
    }
};

module.exports = FlyToFeedback;
