// Generated by gencpp from file aeplanner/aeplannerResult.msg
// DO NOT EDIT!


#ifndef AEPLANNER_MESSAGE_AEPLANNERRESULT_H
#define AEPLANNER_MESSAGE_AEPLANNERRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/PoseArray.h>
#include <std_msgs/Duration.h>
#include <std_msgs/Duration.h>
#include <std_msgs/Duration.h>

namespace aeplanner
{
template <class ContainerAllocator>
struct aeplannerResult_
{
  typedef aeplannerResult_<ContainerAllocator> Type;

  aeplannerResult_()
    : pose()
    , frontiers()
    , is_clear(false)
    , sampling_time()
    , planning_time()
    , collision_check_time()
    , tree_size(0)  {
    }
  aeplannerResult_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , frontiers(_alloc)
    , is_clear(false)
    , sampling_time(_alloc)
    , planning_time(_alloc)
    , collision_check_time(_alloc)
    , tree_size(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef  ::geometry_msgs::PoseArray_<ContainerAllocator>  _frontiers_type;
  _frontiers_type frontiers;

   typedef uint8_t _is_clear_type;
  _is_clear_type is_clear;

   typedef  ::std_msgs::Duration_<ContainerAllocator>  _sampling_time_type;
  _sampling_time_type sampling_time;

   typedef  ::std_msgs::Duration_<ContainerAllocator>  _planning_time_type;
  _planning_time_type planning_time;

   typedef  ::std_msgs::Duration_<ContainerAllocator>  _collision_check_time_type;
  _collision_check_time_type collision_check_time;

   typedef int32_t _tree_size_type;
  _tree_size_type tree_size;





  typedef boost::shared_ptr< ::aeplanner::aeplannerResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aeplanner::aeplannerResult_<ContainerAllocator> const> ConstPtr;

}; // struct aeplannerResult_

typedef ::aeplanner::aeplannerResult_<std::allocator<void> > aeplannerResult;

typedef boost::shared_ptr< ::aeplanner::aeplannerResult > aeplannerResultPtr;
typedef boost::shared_ptr< ::aeplanner::aeplannerResult const> aeplannerResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aeplanner::aeplannerResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aeplanner::aeplannerResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aeplanner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'aeplanner': ['/home/idris/catkin_ws/src/aeplanner/aeplanner/msg', '/home/idris/catkin_ws/devel/.private/aeplanner/share/aeplanner/msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/melodic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aeplanner::aeplannerResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aeplanner::aeplannerResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aeplanner::aeplannerResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aeplanner::aeplannerResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aeplanner::aeplannerResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aeplanner::aeplannerResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aeplanner::aeplannerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9455a2480a247f4ce7d9ba7774e790ba";
  }

  static const char* value(const ::aeplanner::aeplannerResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9455a2480a247f4cULL;
  static const uint64_t static_value2 = 0xe7d9ba7774e790baULL;
};

template<class ContainerAllocator>
struct DataType< ::aeplanner::aeplannerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aeplanner/aeplannerResult";
  }

  static const char* value(const ::aeplanner::aeplannerResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aeplanner::aeplannerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the result\n\
geometry_msgs/PoseStamped pose\n\
geometry_msgs/PoseArray frontiers\n\
bool is_clear\n\
std_msgs/Duration sampling_time\n\
std_msgs/Duration planning_time\n\
std_msgs/Duration collision_check_time\n\
int32 tree_size\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseArray\n\
# An array of poses with a header for global reference.\n\
\n\
Header header\n\
\n\
Pose[] poses\n\
\n\
================================================================================\n\
MSG: std_msgs/Duration\n\
duration data\n\
";
  }

  static const char* value(const ::aeplanner::aeplannerResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aeplanner::aeplannerResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.frontiers);
      stream.next(m.is_clear);
      stream.next(m.sampling_time);
      stream.next(m.planning_time);
      stream.next(m.collision_check_time);
      stream.next(m.tree_size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct aeplannerResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aeplanner::aeplannerResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aeplanner::aeplannerResult_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "frontiers: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseArray_<ContainerAllocator> >::stream(s, indent + "  ", v.frontiers);
    s << indent << "is_clear: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_clear);
    s << indent << "sampling_time: ";
    s << std::endl;
    Printer< ::std_msgs::Duration_<ContainerAllocator> >::stream(s, indent + "  ", v.sampling_time);
    s << indent << "planning_time: ";
    s << std::endl;
    Printer< ::std_msgs::Duration_<ContainerAllocator> >::stream(s, indent + "  ", v.planning_time);
    s << indent << "collision_check_time: ";
    s << std::endl;
    Printer< ::std_msgs::Duration_<ContainerAllocator> >::stream(s, indent + "  ", v.collision_check_time);
    s << indent << "tree_size: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tree_size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AEPLANNER_MESSAGE_AEPLANNERRESULT_H
