// Generated by gencpp from file aeplanner/aeplannerGoal.msg
// DO NOT EDIT!


#ifndef AEPLANNER_MESSAGE_AEPLANNERGOAL_H
#define AEPLANNER_MESSAGE_AEPLANNERGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace aeplanner
{
template <class ContainerAllocator>
struct aeplannerGoal_
{
  typedef aeplannerGoal_<ContainerAllocator> Type;

  aeplannerGoal_()
    : header()
    , actions_taken(0)  {
    }
  aeplannerGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , actions_taken(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _actions_taken_type;
  _actions_taken_type actions_taken;





  typedef boost::shared_ptr< ::aeplanner::aeplannerGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aeplanner::aeplannerGoal_<ContainerAllocator> const> ConstPtr;

}; // struct aeplannerGoal_

typedef ::aeplanner::aeplannerGoal_<std::allocator<void> > aeplannerGoal;

typedef boost::shared_ptr< ::aeplanner::aeplannerGoal > aeplannerGoalPtr;
typedef boost::shared_ptr< ::aeplanner::aeplannerGoal const> aeplannerGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aeplanner::aeplannerGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aeplanner::aeplannerGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aeplanner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'aeplanner': ['/home/idris/catkin_ws/src/aeplanner/aeplanner/msg', '/home/idris/catkin_ws/devel/.private/aeplanner/share/aeplanner/msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/melodic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aeplanner::aeplannerGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aeplanner::aeplannerGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aeplanner::aeplannerGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aeplanner::aeplannerGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aeplanner::aeplannerGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aeplanner::aeplannerGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aeplanner::aeplannerGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8af38301301363c106591cce65e2a43e";
  }

  static const char* value(const ::aeplanner::aeplannerGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8af38301301363c1ULL;
  static const uint64_t static_value2 = 0x06591cce65e2a43eULL;
};

template<class ContainerAllocator>
struct DataType< ::aeplanner::aeplannerGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aeplanner/aeplannerGoal";
  }

  static const char* value(const ::aeplanner::aeplannerGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aeplanner::aeplannerGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the goal\n\
Header header\n\
int32 actions_taken\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::aeplanner::aeplannerGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aeplanner::aeplannerGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.actions_taken);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct aeplannerGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aeplanner::aeplannerGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aeplanner::aeplannerGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "actions_taken: ";
    Printer<int32_t>::stream(s, indent + "  ", v.actions_taken);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AEPLANNER_MESSAGE_AEPLANNERGOAL_H
