// Generated by gencpp from file aeplanner/ReevaluateRequest.msg
// DO NOT EDIT!


#ifndef AEPLANNER_MESSAGE_REEVALUATEREQUEST_H
#define AEPLANNER_MESSAGE_REEVALUATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace aeplanner
{
template <class ContainerAllocator>
struct ReevaluateRequest_
{
  typedef ReevaluateRequest_<ContainerAllocator> Type;

  ReevaluateRequest_()
    : point()  {
    }
  ReevaluateRequest_(const ContainerAllocator& _alloc)
    : point(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _point_type;
  _point_type point;





  typedef boost::shared_ptr< ::aeplanner::ReevaluateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aeplanner::ReevaluateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ReevaluateRequest_

typedef ::aeplanner::ReevaluateRequest_<std::allocator<void> > ReevaluateRequest;

typedef boost::shared_ptr< ::aeplanner::ReevaluateRequest > ReevaluateRequestPtr;
typedef boost::shared_ptr< ::aeplanner::ReevaluateRequest const> ReevaluateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aeplanner::ReevaluateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aeplanner::ReevaluateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aeplanner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'aeplanner': ['/home/idris/catkin_ws/src/aeplanner/aeplanner/msg', '/home/idris/catkin_ws/devel/.private/aeplanner/share/aeplanner/msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/melodic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aeplanner::ReevaluateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aeplanner::ReevaluateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aeplanner::ReevaluateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aeplanner::ReevaluateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aeplanner::ReevaluateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aeplanner::ReevaluateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aeplanner::ReevaluateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a7c84ff13976aa04656e56e300124444";
  }

  static const char* value(const ::aeplanner::ReevaluateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa7c84ff13976aa04ULL;
  static const uint64_t static_value2 = 0x656e56e300124444ULL;
};

template<class ContainerAllocator>
struct DataType< ::aeplanner::ReevaluateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aeplanner/ReevaluateRequest";
  }

  static const char* value(const ::aeplanner::ReevaluateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aeplanner::ReevaluateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] point\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::aeplanner::ReevaluateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aeplanner::ReevaluateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReevaluateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aeplanner::ReevaluateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aeplanner::ReevaluateRequest_<ContainerAllocator>& v)
  {
    s << indent << "point[]" << std::endl;
    for (size_t i = 0; i < v.point.size(); ++i)
    {
      s << indent << "  point[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.point[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AEPLANNER_MESSAGE_REEVALUATEREQUEST_H
