// Generated by gencpp from file aeplanner/Reevaluate.msg
// DO NOT EDIT!


#ifndef AEPLANNER_MESSAGE_REEVALUATE_H
#define AEPLANNER_MESSAGE_REEVALUATE_H

#include <ros/service_traits.h>


#include <aeplanner/ReevaluateRequest.h>
#include <aeplanner/ReevaluateResponse.h>


namespace aeplanner
{

struct Reevaluate
{

typedef ReevaluateRequest Request;
typedef ReevaluateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Reevaluate
} // namespace aeplanner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aeplanner::Reevaluate > {
  static const char* value()
  {
    return "2280f373a6f208a73c4e2808d32c69a4";
  }

  static const char* value(const ::aeplanner::Reevaluate&) { return value(); }
};

template<>
struct DataType< ::aeplanner::Reevaluate > {
  static const char* value()
  {
    return "aeplanner/Reevaluate";
  }

  static const char* value(const ::aeplanner::Reevaluate&) { return value(); }
};


// service_traits::MD5Sum< ::aeplanner::ReevaluateRequest> should match 
// service_traits::MD5Sum< ::aeplanner::Reevaluate > 
template<>
struct MD5Sum< ::aeplanner::ReevaluateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aeplanner::Reevaluate >::value();
  }
  static const char* value(const ::aeplanner::ReevaluateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aeplanner::ReevaluateRequest> should match 
// service_traits::DataType< ::aeplanner::Reevaluate > 
template<>
struct DataType< ::aeplanner::ReevaluateRequest>
{
  static const char* value()
  {
    return DataType< ::aeplanner::Reevaluate >::value();
  }
  static const char* value(const ::aeplanner::ReevaluateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aeplanner::ReevaluateResponse> should match 
// service_traits::MD5Sum< ::aeplanner::Reevaluate > 
template<>
struct MD5Sum< ::aeplanner::ReevaluateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aeplanner::Reevaluate >::value();
  }
  static const char* value(const ::aeplanner::ReevaluateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aeplanner::ReevaluateResponse> should match 
// service_traits::DataType< ::aeplanner::Reevaluate > 
template<>
struct DataType< ::aeplanner::ReevaluateResponse>
{
  static const char* value()
  {
    return DataType< ::aeplanner::Reevaluate >::value();
  }
  static const char* value(const ::aeplanner::ReevaluateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AEPLANNER_MESSAGE_REEVALUATE_H
