(cl:defpackage rpl_exploration-msg
  (:use )
  (:export
   "<FLYTOACTION>"
   "FLYTOACTION"
   "<FLYTOACTIONFEEDBACK>"
   "FLYTOACTIONFEEDBACK"
   "<FLYTOACTIONGOAL>"
   "FLYTOACTIONGOAL"
   "<FLYTOACTIONRESULT>"
   "FLYTOACTIONRESULT"
   "<FLYTOFEEDBACK>"
   "FLYTOFEEDBACK"
   "<FLYTOGOAL>"
   "FLYTOGOAL"
   "<FLYTORESULT>"
   "FLYTORESULT"
  ))

