; Auto-generated. Do not edit!


(cl:in-package rpl_exploration-msg)


;//! \htmlinclude FlyToResult.msg.html

(cl:defclass <FlyToResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass FlyToResult (<FlyToResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FlyToResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FlyToResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rpl_exploration-msg:<FlyToResult> is deprecated: use rpl_exploration-msg:FlyToResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FlyToResult>) ostream)
  "Serializes a message object of type '<FlyToResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FlyToResult>) istream)
  "Deserializes a message object of type '<FlyToResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FlyToResult>)))
  "Returns string type for a message object of type '<FlyToResult>"
  "rpl_exploration/FlyToResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FlyToResult)))
  "Returns string type for a message object of type 'FlyToResult"
  "rpl_exploration/FlyToResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FlyToResult>)))
  "Returns md5sum for a message object of type '<FlyToResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FlyToResult)))
  "Returns md5sum for a message object of type 'FlyToResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FlyToResult>)))
  "Returns full string definition for message of type '<FlyToResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FlyToResult)))
  "Returns full string definition for message of type 'FlyToResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FlyToResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FlyToResult>))
  "Converts a ROS message object to a list"
  (cl:list 'FlyToResult
))
