; Auto-generated. Do not edit!


(cl:in-package rpl_exploration-msg)


;//! \htmlinclude FlyToFeedback.msg.html

(cl:defclass <FlyToFeedback> (roslisp-msg-protocol:ros-message)
  ((distance_to_target
    :reader distance_to_target
    :initarg :distance_to_target
    :type cl:float
    :initform 0.0))
)

(cl:defclass FlyToFeedback (<FlyToFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FlyToFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FlyToFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rpl_exploration-msg:<FlyToFeedback> is deprecated: use rpl_exploration-msg:FlyToFeedback instead.")))

(cl:ensure-generic-function 'distance_to_target-val :lambda-list '(m))
(cl:defmethod distance_to_target-val ((m <FlyToFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rpl_exploration-msg:distance_to_target-val is deprecated.  Use rpl_exploration-msg:distance_to_target instead.")
  (distance_to_target m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FlyToFeedback>) ostream)
  "Serializes a message object of type '<FlyToFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'distance_to_target))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FlyToFeedback>) istream)
  "Deserializes a message object of type '<FlyToFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'distance_to_target) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FlyToFeedback>)))
  "Returns string type for a message object of type '<FlyToFeedback>"
  "rpl_exploration/FlyToFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FlyToFeedback)))
  "Returns string type for a message object of type 'FlyToFeedback"
  "rpl_exploration/FlyToFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FlyToFeedback>)))
  "Returns md5sum for a message object of type '<FlyToFeedback>"
  "7162840b236da25d3abd73cc2177a48e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FlyToFeedback)))
  "Returns md5sum for a message object of type 'FlyToFeedback"
  "7162840b236da25d3abd73cc2177a48e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FlyToFeedback>)))
  "Returns full string definition for message of type '<FlyToFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32 distance_to_target~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FlyToFeedback)))
  "Returns full string definition for message of type 'FlyToFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32 distance_to_target~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FlyToFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FlyToFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'FlyToFeedback
    (cl:cons ':distance_to_target (distance_to_target msg))
))
