// Generated by gencpp from file rpl_exploration/FlyToFeedback.msg
// DO NOT EDIT!


#ifndef RPL_EXPLORATION_MESSAGE_FLYTOFEEDBACK_H
#define RPL_EXPLORATION_MESSAGE_FLYTOFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rpl_exploration
{
template <class ContainerAllocator>
struct FlyToFeedback_
{
  typedef FlyToFeedback_<ContainerAllocator> Type;

  FlyToFeedback_()
    : distance_to_target(0.0)  {
    }
  FlyToFeedback_(const ContainerAllocator& _alloc)
    : distance_to_target(0.0)  {
  (void)_alloc;
    }



   typedef float _distance_to_target_type;
  _distance_to_target_type distance_to_target;





  typedef boost::shared_ptr< ::rpl_exploration::FlyToFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rpl_exploration::FlyToFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct FlyToFeedback_

typedef ::rpl_exploration::FlyToFeedback_<std::allocator<void> > FlyToFeedback;

typedef boost::shared_ptr< ::rpl_exploration::FlyToFeedback > FlyToFeedbackPtr;
typedef boost::shared_ptr< ::rpl_exploration::FlyToFeedback const> FlyToFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rpl_exploration::FlyToFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rpl_exploration::FlyToFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rpl_exploration

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'rpl_exploration': ['/home/idris/catkin_ws/devel/.private/rpl_exploration/share/rpl_exploration/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rpl_exploration::FlyToFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rpl_exploration::FlyToFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rpl_exploration::FlyToFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rpl_exploration::FlyToFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rpl_exploration::FlyToFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rpl_exploration::FlyToFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rpl_exploration::FlyToFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7162840b236da25d3abd73cc2177a48e";
  }

  static const char* value(const ::rpl_exploration::FlyToFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7162840b236da25dULL;
  static const uint64_t static_value2 = 0x3abd73cc2177a48eULL;
};

template<class ContainerAllocator>
struct DataType< ::rpl_exploration::FlyToFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rpl_exploration/FlyToFeedback";
  }

  static const char* value(const ::rpl_exploration::FlyToFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rpl_exploration::FlyToFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define a feedback message\n\
float32 distance_to_target\n\
\n\
";
  }

  static const char* value(const ::rpl_exploration::FlyToFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rpl_exploration::FlyToFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance_to_target);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FlyToFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rpl_exploration::FlyToFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rpl_exploration::FlyToFeedback_<ContainerAllocator>& v)
  {
    s << indent << "distance_to_target: ";
    Printer<float>::stream(s, indent + "  ", v.distance_to_target);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RPL_EXPLORATION_MESSAGE_FLYTOFEEDBACK_H
