// Generated by gencpp from file rpl_exploration/FlyToResult.msg
// DO NOT EDIT!


#ifndef RPL_EXPLORATION_MESSAGE_FLYTORESULT_H
#define RPL_EXPLORATION_MESSAGE_FLYTORESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rpl_exploration
{
template <class ContainerAllocator>
struct FlyToResult_
{
  typedef FlyToResult_<ContainerAllocator> Type;

  FlyToResult_()
    {
    }
  FlyToResult_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::rpl_exploration::FlyToResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rpl_exploration::FlyToResult_<ContainerAllocator> const> ConstPtr;

}; // struct FlyToResult_

typedef ::rpl_exploration::FlyToResult_<std::allocator<void> > FlyToResult;

typedef boost::shared_ptr< ::rpl_exploration::FlyToResult > FlyToResultPtr;
typedef boost::shared_ptr< ::rpl_exploration::FlyToResult const> FlyToResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rpl_exploration::FlyToResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rpl_exploration::FlyToResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rpl_exploration

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'rpl_exploration': ['/home/idris/catkin_ws/devel/.private/rpl_exploration/share/rpl_exploration/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rpl_exploration::FlyToResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rpl_exploration::FlyToResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rpl_exploration::FlyToResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rpl_exploration::FlyToResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rpl_exploration::FlyToResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rpl_exploration::FlyToResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rpl_exploration::FlyToResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::rpl_exploration::FlyToResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::rpl_exploration::FlyToResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rpl_exploration/FlyToResult";
  }

  static const char* value(const ::rpl_exploration::FlyToResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rpl_exploration::FlyToResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the result\n\
";
  }

  static const char* value(const ::rpl_exploration::FlyToResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rpl_exploration::FlyToResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FlyToResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rpl_exploration::FlyToResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::rpl_exploration::FlyToResult_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // RPL_EXPLORATION_MESSAGE_FLYTORESULT_H
